#!/bin/bash

set -e
 
echo $GUARD_COOKIE_SECRET
echo $GUARD_DEFAULT_CALLBACK_URL
echo $GUARD_UAA_URL
echo $GUARD_CLIENT_KEY
echo $GUARD_CLIENT_SECRET
echo $GUARD_BROKER_USERNAME
echo $GUARD_BROKER_PASSWORD
echo $GUARD_ROUTE_SERVICE_URL